#!/bin/sh

set -e

echo "I: adding another test user for reproducibility"

NEWUID=$(($(id -u pbuilder) + 1))
NEWGID=$(($(id -g pbuilder) + 1))

groupadd -g "$NEWGID" -o another-group
useradd -g another-group -u "$NEWUID" -d /tmp/buildd -o another-user
chown -R "$NEWUID:$NEWGID" /tmp/buildd

apt-get install sudo
cat >/etc/sudoers.d/pbuser <<EOF
Defaults umask=0002
Defaults umask_override
pbuilder ALL=(another-user:another-group) NOPASSWD: ALL
EOF

mv /usr/bin/dpkg-buildpackage /usr/bin/dpkg-buildpackage.real
cat >/usr/bin/dpkg-buildpackage <<EOF
sudo -E -u another-user -g another-group /usr/bin/dpkg-buildpackage.real "\$@"
EOF
chmod +x /usr/bin/dpkg-buildpackage
