#!/bin/sh
# B92_debbindiff: run debbindiff if needed
#
# We run this hook from the chroot as we can install the version
# of debbindiff that matches our build environment; and get the latest
# improvements if it's unstable.

[ -f /tmp/buildd/initial_build.tar ] || exit 0

echo "I: unpacking initial build material"
mkdir -p /tmp/initial_build
tar -C /tmp/initial_build -xf /tmp/buildd/initial_build.tar
rm /tmp/buildd/initial_build.tar

echo "I: installing debbindiff and running it on the package"
apt-get install -y --force-yes sudo debbindiff 2>&1 > /dev/null
touch /tmp/buildd/debbindiff.html 
chown nobody /tmp/buildd/debbindiff.html
if sudo -u nobody debbindiff --html /tmp/buildd/debbindiff.html /tmp/initial_build/*.changes /tmp/buildd/*.changes; then
	echo
	echo "                              _            _ _     _      "
	echo " _ __ ___ _ __  _ __ ___   __| |_   _  ___(_) |__ | | ___ "
	echo "| '__/ _ \ '_ \| '__/ _ \ / _\` | | | |/ __| | '_ \| |/ _ \\"
	echo "| | |  __/ |_) | | | (_) | (_| | |_| | (__| | |_) | |  __/"
	echo "|_|  \___| .__/|_|  \___/ \__,_|\__,_|\___|_|_.__/|_|\___|"
	echo "         |_|                                              "
	echo
	rm -f /tmp/buildd/debbindiff.html
fi
