#!/bin/sh
# Since Sublime is fucking insane and can't handle symlinks for the User
# directory, we'll need to manually copy stuff over to .dotfiles.
rm -rf $ZSH/sublime2/User
cp -R ~/.config/sublime-text-2/Packages/User $ZSH/sublime2/User
