#!/bin/bash
# example file to be used with --hookdir
#
# try to install the resulting debs.

apt-get install apt
echo "Trying to install resulting packages and test upgrades"
set -ex

BUILDDIR="${BUILDDIR:-/tmp/buildd}"

PKGNAMES=$(cd "$BUILDDIR" && ls -1 *.deb | sed 's/_.*$//' )

# install-remove check
apt install "$BUILDDIR"/*.deb
apt remove $PKGNAMES

# install-purge check
apt install "$BUILDDIR"/*.deb
apt purge $PKGNAMES

# upgrade-remove check
apt install -y "${APTGETOPT[@]}"  $PKGNAMES || true
apt install "$BUILDDIR"/*.deb
apt remove $PKGNAMES

# upgrade-purge check
apt install -y "${APTGETOPT[@]}" $PKGNAMES || true
apt install "$BUILDDIR"/*.deb
apt purge $PKGNAMES
